POST http://localhost:3001/resources
Content-Type: application/json

{
  "title": "Hello world",
  "content": "HI"
}
### 
DELETE http://localhost:3002/.netlify/functions/api/resources/blog
Content-Type: application/json